application: benetag-rhok
version: 3
runtime: python27 
api_version: 1
threadsafe: false

libraries:
- name: django
  version: "1.2"
  
- name: PIL
  version: "1.1.7"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts
  
- url: /BeneTagScreenshots
  static_dir: BeneTagScreenshots
  
- url: /static
  static_dir: static

- url: /img
  static_dir: img
  
- url: /.*
  script: hellobenetag.py

error_handlers:  
  - error_code: dos_api_denial
    file: dos_error.html
  
  - error_code: timeout
    file: timeout.html